apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.app.secretName" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- include "platform.selectorLabels" . | nindent 4 }}
type: Opaque
{{- if .Values.app.secretEnv }}
stringData:
  {{- range $key, $value := .Values.app.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
